before_install:
  - sudo apt-get update
  - gem update bundler
bundler_args: --without development
language: ruby
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: 1.9.2
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
script: bundle exec rake spec
